# Generated by Django 2.2.1 on 2019-05-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=45)),
                ('user_nickname', models.CharField(max_length=45)),
                ('user_password', models.CharField(default=None, max_length=200)),
                ('social_id', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
