# Generated by Django 2.2.1 on 2019-05-24 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190522_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user', to='users.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to='users.User')),
            ],
            options={
                'db_table': 'blocked_users',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='block_users',
            field=models.ManyToManyField(related_name='user', through='users.BlockedUser', to='users.User'),
        ),
    ]
