# Generated by Django 2.2.1 on 2019-05-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190524_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
