# Generated by Django 2.2.1 on 2019-05-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
