# Generated by Django 2.2.1 on 2019-05-27 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('users', '0006_auto_20190525_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_Community', to='community.Community'),
        ),
    ]
