# Generated by Django 2.2.1 on 2019-05-27 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        ('users', '0007_user_user_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFavoriteTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_topic', to='topics.Topic')),
                ('topic_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_user', to='users.User')),
            ],
            options={
                'db_table': 'favorite_topic',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_topics',
            field=models.ManyToManyField(related_name='favorite_topics', through='users.MyFavoriteTopic', to='topics.Topic'),
        ),
    ]
