# Generated by Django 2.2.1 on 2019-05-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190527_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
