# Generated by Django 2.2.1 on 2019-05-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(default='topics', max_length=45, null=True),
        ),
    ]
