# Generated by Django 2.2.1 on 2019-05-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=45)),
                ('commu_name', models.CharField(max_length=45)),
                ('location1', models.CharField(default=None, max_length=45, null=True)),
                ('location2', models.CharField(default=None, max_length=45, null=True)),
                ('location3', models.CharField(default=None, max_length=45, null=True)),
            ],
            options={
                'db_table': 'cummunities',
            },
        ),
    ]
