# Generated by Django 2.2.1 on 2019-05-27 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='community',
            table='communities',
        ),
    ]
