# Generated by Django 2.2.1 on 2019-05-31 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_auto_20190530_2039'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.CharField(max_length=200, null=True)),
                ('stage_time', models.CharField(max_length=45)),
                ('select_topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_topic', to='topics.Topic')),
            ],
            options={
                'db_table': 'stages',
            },
        ),
        migrations.CreateModel(
            name='WaitingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('select_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='select_stage', to='stages.Stage')),
                ('waiting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiting_user', to='users.User')),
            ],
            options={
                'db_table': 'waiting_rooms',
            },
        ),
    ]
